name: CICD PIPELINE 
on:
   push: 
        branches: ["main"]

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        strategy:
            matrix: 
                node-version: [20,22.24]
                
        steps:
            - name: checkout code 
              uses: actions/checkout@v4
              with: 
                fetch-depth: 0
                
                
            - name: setup node${{matrix.node-version}}
              uses: actions/setup-node@v6
              with:
                node-version: ${{matrix.node-version}}     

            - name: install frontend dependicies
              working-directory: ./frontend 
              run: npm  ci

            - name: install backend dependicies
              working-directory: ./backend
              run: npm ci
              
            - name: build backend
              working-directory: ./backend
              run: npm run build --if-present

            - name: build frontend
              working-directory: ./frontend
              run: npm run build --if-present

            - name: build frontend docker image
              working-directory: ./frontend
              run: docker build -f ./frontend/Dockerfile -t myapp:latest ./frontend
              
            - name: build backend docker image
              working-directory: ./backend
              run: docker build -f ./backend/Dockerfile -t myapp:latest ./backend

              